Repository kokonior/CSS-Projects, pull requests merged in 2021-10, with the labels that each got.

#1 Create Sandi L. Putra
  Sandi L. Putra
Labels: hacktoberfest-accepted

#3 Create triangle.css
  triangle.css
Labels: hacktoberfest-accepted, Create

#9 Update README.md
  README.md
Labels: hacktoberfest-accepted

#8 Update triangle.css
  triangle.css
Labels: hacktoberfest-accepted

#7 Update triangle.css
  triangle.css
Labels: hacktoberfest-accepted

#6 add scroll effect
  scroll-effect/index.html
  scroll-effect/style.css
Labels: good first issue, hacktoberfest-accepted

#5 Create dropdown-ui
  dropdown-ui
Labels: hacktoberfest-accepted, Create

#4 add costume css
  custome.css
Labels: enhancement, hacktoberfest-accepted

#11 Create jarkomxx.css
  jarkomxx.css
Labels: hacktoberfest-accepted, Create

#12 Added a new project
  CSS and HTML project/client.jpg
  CSS and HTML project/client2.jpg
  CSS and HTML project/client3.jpg
  CSS and HTML project/client4.jpg
  CSS and HTML project/client5.png
  CSS and HTML project/contact-us.jpg
  CSS and HTML project/contact.jpg
  CSS and HTML project/deliveryboy.webp
  CSS and HTML project/img1.jpg
  CSS and HTML project/img2.jpeg
  CSS and HTML project/img3.jpg
  CSS and HTML project/img4.jpg
  CSS and HTML project/index.html
  CSS and HTML project/logo.png
  CSS and HTML project/logo2.webp
  CSS and HTML project/phone.css
  CSS and HTML project/style.css
Labels: enhancement, hacktoberfest-accepted

#13 html+css+javascript project
  Dummy Website Project/gym 2.webp
  Dummy Website Project/gym1.webp
  Dummy Website Project/index.html
  Dummy Website Project/people-2604149_1920.jpg
  Dummy Website Project/settings.json
  Musical Instrument/1.html
  Musical Instrument/index.html
  Musical Instrument/notes/notes_A.mp3
  Musical Instrument/notes/notes_Ab.mp3
  Musical Instrument/notes/notes_B.mp3
  Musical Instrument/notes/notes_Bb.mp3
  Musical Instrument/notes/notes_C.mp3
  Musical Instrument/notes/notes_D.mp3
  Musical Instrument/notes/notes_E.mp3
  Musical Instrument/notes/notes_Eb.mp3
  Musical Instrument/notes/notes_F.mp3
  Musical Instrument/notes/notes_G.mp3
  Musical Instrument/notes/notes_Gb.mp3
  Musical Instrument/script.js
  Musical Instrument/style.css
Labels: enhancement, hacktoberfest-accepted

#14 Add RGB Color Guessing Game Project
  RGB Color Guessing Game/README.md
  RGB Color Guessing Game/colorGameProject.css
  RGB Color Guessing Game/colorGameProject.js
  RGB Color Guessing Game/index.html
Labels: enhancement, hacktoberfest-accepted

#15 Add Tic Tac Toe Game Project
  Tic Tac Toe Game/README.md
  Tic Tac Toe Game/index.html
  Tic Tac Toe Game/tic-tac-toe.css
  Tic Tac Toe Game/tic-tac-toe.js
Labels: enhancement, hacktoberfest-accepted

#16 Created a CSS styled webpage following a newspaper's theme.
  NewsPaper-Theme/Readme.md
  NewsPaper-Theme/assets/working-demo.png
  NewsPaper-Theme/index.html
  NewsPaper-Theme/styles.css
Labels: hacktoberfest-accepted, Create

#17 Infinity change moved color box
  change_color_animation.css
Labels: enhancement, hacktoberfest-accepted

#18 calculator made in javascript
  calc.html
Labels: hacktoberfest-accepted

#19 Update index.html
  CSS and HTML project/index.html
Labels: enhancement, hacktoberfest-accepted

#20 switch background color
  cp2940.css
Labels: enhancement, hacktoberfest-accepted

#21 transparant background
  transparant_condrok.css
Labels: hacktoberfest-accepted

#22 update css header
  custome.css
Labels: hacktoberfest-accepted

#24 Update custome.css
  custome.css
Labels: hacktoberfest-accepted

#25 Create DMuhammad
  DMuhammad
Labels: hacktoberfest-accepted

#26 Added a basic todo list project
  To-Do-List-Web-Dev-Project-main.zip
Labels: hacktoberfest-accepted

#66 Added css loading animation
  CSS_Loader/loader.css
  CSS_Loader/loader.html
Labels: hacktoberfest-accepted
